name: localconnect
description: A new Flutter project.
publish_to: 'none' 
version: 1.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # json_rpc_2: ^3.0.2
  # web_socket_channel: ^2.4.0

  # simple_peer: ^0.0.13
  # peerdart: ^0.5.3
  network_discovery: ^1.0.0
  device_info_plus: ^9.0.3
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.1
  flutter_markdown: ^0.6.17+3
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.1.14
  adaptive_theme: ^3.4.0
  toggle_switch: ^2.1.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # flutter_launcher_icons: ^0.13.1
  # change_app_package_name: ^1.1.0
  # rename_app: ^1.1.0
  # flutter_app_name: ^0.1.1
  # rename: ^2.1.1

flutter:

  uses-material-design: true

  # assets:
  #   - assets/logo.png
  #   - assets/logo-mob.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_app_name:
  name: "Local Connect"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-mob.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/logo-mob.png"
  adaptive_icon_background: "#FF5722"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"